// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// snippet.show
import Foundation
import GoogleCloudMigrationCenterV1
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc

func sample(
  client: MigrationCenterClient, projectId: String, locationId: String, sourceId: String,
  errorFrameId: String
) async throws {
  let response = try await client.getErrorFrame(
    request: GetErrorFrameRequest()
      .with {
        $0.name =
          "projects/\(projectId)/locations/\(locationId)/sources/\(sourceId)/errorFrames/\(errorFrameId)"
      }
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudMigrationCenterV1.MigrationCenterClient()
      try await sample(
        client: client, projectId: "[placeholder]", locationId: "[placeholder]",
        sourceId: "[placeholder]", errorFrameId: "[placeholder]")
    } catch {
      print("Error: \(error)")
    }
  }
}
