// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Contains data reported from an inventory source on an asset.
public struct AssetFrame: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The time the data was reported.
  public var reportTime: GoogleCloudWkt.Timestamp? = nil

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Generic asset attributes.
  public var attributes: [Swift.String: Swift.String] = [:]

  /// Asset performance data samples.
  /// Samples that are from more than 40 days ago or after tomorrow are ignored.
  public var performanceSamples: [PerformanceSample] = []

  /// Optional. Trace token is optionally provided to assist with debugging and
  /// traceability.
  public var traceToken: Swift.String = Swift.String()

  /// The internal data of the frame is a oneof field depending on the type
  /// of asset information in the frame.
  public var frameData: OneOf_FrameData? = nil

  /// Initialize a new instance of `AssetFrame`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AssetFrame().with { $0.machineDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case machineDetails = "machineDetails"
    case reportTime = "reportTime"
    case labels = "labels"
    case attributes = "attributes"
    case performanceSamples = "performanceSamples"
    case traceToken = "traceToken"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.reportTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .reportTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.attributes = try container.decode([Swift.String: Swift.String].self, forKey: .attributes)
    self.performanceSamples = try container.decode(
      [PerformanceSample].self, forKey: .performanceSamples)
    self.traceToken = try container.decode(Swift.String.self, forKey: .traceToken)

    var frameData: OneOf_FrameData? = nil
    let frameDataCheckAndSet = {
      if frameData != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'frameData'"))
      }
      frameData = $0
    }
    if let machineDetails = try container.decodeIfPresent(
      MachineDetails?.self, forKey: .machineDetails)
    {
      try frameDataCheckAndSet(.machineDetails(machineDetails))
    }
    self.frameData = frameData
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.reportTime, forKey: .reportTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encode(self.performanceSamples, forKey: .performanceSamples)
    try container.encode(self.traceToken, forKey: .traceToken)

    if let choice = self.frameData {
      switch choice {
      case .machineDetails(let value):
        try container.encode(value, forKey: .machineDetails)
      }
    }
  }

  /// The internal data of the frame is a oneof field depending on the type
  /// of asset information in the frame.
  public enum OneOf_FrameData: Codable, Equatable, Sendable {
    /// Asset information specific for virtual machines.
    indirect case machineDetails(MachineDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.AssetFrame"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
