// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An asset represents a resource in your environment. Asset types include
/// virtual machines and databases.
public struct Asset: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full name of the asset.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp when the asset was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The timestamp when the asset was last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Generic asset attributes.
  public var attributes: [Swift.String: Swift.String] = [:]

  /// Output only. The list of insights associated with the asset.
  public var insightList: InsightList? = nil

  /// Output only. Performance data for the asset.
  public var performanceData: AssetPerformanceData? = nil

  /// Output only. The list of sources contributing to the asset.
  public var sources: [Swift.String] = []

  /// Output only. The list of groups that the asset is assigned to.
  public var assignedGroups: [Swift.String] = []

  /// The internal information of an asset. Only one field can be specified
  /// with different attributes based on the type of the asset.
  public var assetDetails: OneOf_AssetDetails? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Asset`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Asset().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let attributes = CodingKeys(stringValue: "attributes")
    static let machineDetails = CodingKeys(stringValue: "machineDetails")
    static let insightList = CodingKeys(stringValue: "insightList")
    static let performanceData = CodingKeys(stringValue: "performanceData")
    static let sources = CodingKeys(stringValue: "sources")
    static let assignedGroups = CodingKeys(stringValue: "assignedGroups")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "attributes",
      "machineDetails",
      "insightList",
      "performanceData",
      "sources",
      "assignedGroups",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .attributes)
    {
      self.attributes = value
    }
    self.insightList = try container.decodeIfPresent(InsightList.self, forKey: .insightList)
    self.performanceData = try container.decodeIfPresent(
      AssetPerformanceData.self, forKey: .performanceData)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .sources) {
      self.sources = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .assignedGroups) {
      self.assignedGroups = value
    }

    var assetDetails: OneOf_AssetDetails? = nil
    let assetDetailsCheckAndSet = {
      if assetDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'assetDetails'"))
      }
      assetDetails = $0
    }
    if let machineDetails = try container.decodeIfPresent(
      MachineDetails?.self, forKey: .machineDetails)
    {
      try assetDetailsCheckAndSet(.machineDetails(machineDetails))
    }
    self.assetDetails = assetDetails
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encodeIfPresent(self.insightList, forKey: .insightList)
    try container.encodeIfPresent(self.performanceData, forKey: .performanceData)
    try container.encode(self.sources, forKey: .sources)
    try container.encode(self.assignedGroups, forKey: .assignedGroups)

    if let choice = self.assetDetails {
      switch choice {
      case .machineDetails(let value):
        try container.encode(value, forKey: .machineDetails)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The internal information of an asset. Only one field can be specified
  /// with different attributes based on the type of the asset.
  public enum OneOf_AssetDetails: Codable, Equatable, Sendable {
    /// Output only. Asset information specific for virtual and physical
    /// machines.
    indirect case machineDetails(MachineDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.Asset"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
