// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An asset represents a resource in your environment. Asset types include
/// virtual machines and databases.
public struct Asset: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The full name of the asset.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp when the asset was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp when the asset was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Generic asset attributes.
  public var attributes: [Swift.String: Swift.String] = [:]

  /// Output only. The list of insights associated with the asset.
  public var insightList: InsightList? = nil

  /// Output only. Performance data for the asset.
  public var performanceData: AssetPerformanceData? = nil

  /// Output only. The list of sources contributing to the asset.
  public var sources: [Swift.String] = []

  /// Output only. The list of groups that the asset is assigned to.
  public var assignedGroups: [Swift.String] = []

  /// The internal information of an asset. Only one field can be specified
  /// with different attributes based on the type of the asset.
  public var assetDetails: OneOf_AssetDetails? = nil

  /// Initialize a new instance of `Asset`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Asset().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case attributes = "attributes"
    case machineDetails = "machineDetails"
    case insightList = "insightList"
    case performanceData = "performanceData"
    case sources = "sources"
    case assignedGroups = "assignedGroups"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.attributes = try container.decode([Swift.String: Swift.String].self, forKey: .attributes)
    self.insightList = try container.decodeIfPresent(InsightList.self, forKey: .insightList)
    self.performanceData = try container.decodeIfPresent(
      AssetPerformanceData.self, forKey: .performanceData)
    self.sources = try container.decode([Swift.String].self, forKey: .sources)
    self.assignedGroups = try container.decode([Swift.String].self, forKey: .assignedGroups)

    var assetDetails: OneOf_AssetDetails? = nil
    let assetDetailsCheckAndSet = {
      if assetDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'assetDetails'"))
      }
      assetDetails = $0
    }
    if let machineDetails = try container.decodeIfPresent(
      MachineDetails?.self, forKey: .machineDetails)
    {
      try assetDetailsCheckAndSet(.machineDetails(machineDetails))
    }
    self.assetDetails = assetDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encode(self.insightList, forKey: .insightList)
    try container.encode(self.performanceData, forKey: .performanceData)
    try container.encode(self.sources, forKey: .sources)
    try container.encode(self.assignedGroups, forKey: .assignedGroups)

    if let choice = self.assetDetails {
      switch choice {
      case .machineDetails(let value):
        try container.encode(value, forKey: .machineDetails)
      }
    }
  }

  /// The internal information of an asset. Only one field can be specified
  /// with different attributes based on the type of the asset.
  public enum OneOf_AssetDetails: Codable, Equatable, Sendable {
    /// Output only. Asset information specific for virtual and physical
    /// machines.
    indirect case machineDetails(MachineDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.Asset"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
