// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// Details about the BIOS.
public struct BiosDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// BIOS name.
  /// This fields is deprecated. Please use the `id` field instead.
  @available(*, deprecated)
  public var biosName: Swift.String = Swift.String()

  /// BIOS ID.
  public var id: Swift.String = Swift.String()

  /// BIOS manufacturer.
  public var manufacturer: Swift.String = Swift.String()

  /// BIOS version.
  public var version: Swift.String = Swift.String()

  /// BIOS release date.
  public var releaseDate: GoogleType.Date? = nil

  /// SMBIOS UUID.
  public var smbiosUuid: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BiosDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BiosDetails().with { $0.biosName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let biosName = CodingKeys(stringValue: "biosName")
    static let id = CodingKeys(stringValue: "id")
    static let manufacturer = CodingKeys(stringValue: "manufacturer")
    static let version = CodingKeys(stringValue: "version")
    static let releaseDate = CodingKeys(stringValue: "releaseDate")
    static let smbiosUuid = CodingKeys(stringValue: "smbiosUuid")

    static let _knownKeys: Set<Swift.String> = [
      "biosName",
      "id",
      "manufacturer",
      "version",
      "releaseDate",
      "smbiosUuid",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .biosName) {
      self.biosName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .manufacturer) {
      self.manufacturer = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    self.releaseDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .releaseDate)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .smbiosUuid) {
      self.smbiosUuid = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.biosName, forKey: .biosName)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.manufacturer, forKey: .manufacturer)
    try container.encode(self.version, forKey: .version)
    try container.encodeIfPresent(self.releaseDate, forKey: .releaseDate)
    try container.encode(self.smbiosUuid, forKey: .smbiosUuid)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.BiosDetails"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
