// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Compute Engine target shape descriptor.
public struct ComputeEngineShapeDescriptor: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Memory in mebibytes.
  public var memoryMb: Swift.Int32 = Swift.Int32()

  /// Number of physical cores.
  public var physicalCoreCount: Swift.Int32 = Swift.Int32()

  /// Number of logical cores.
  public var logicalCoreCount: Swift.Int32 = Swift.Int32()

  /// Compute Engine machine series.
  public var series: Swift.String = Swift.String()

  /// Compute Engine machine type.
  public var machineType: Swift.String = Swift.String()

  /// Compute Engine storage. Never empty.
  public var storage: [ComputeStorageDescriptor] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ComputeEngineShapeDescriptor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeEngineShapeDescriptor().with { $0.memoryMb = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let memoryMb = CodingKeys(stringValue: "memoryMb")
    static let physicalCoreCount = CodingKeys(stringValue: "physicalCoreCount")
    static let logicalCoreCount = CodingKeys(stringValue: "logicalCoreCount")
    static let series = CodingKeys(stringValue: "series")
    static let machineType = CodingKeys(stringValue: "machineType")
    static let storage = CodingKeys(stringValue: "storage")

    static let _knownKeys: Set<Swift.String> = [
      "memoryMb",
      "physicalCoreCount",
      "logicalCoreCount",
      "series",
      "machineType",
      "storage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .memoryMb) {
      self.memoryMb = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .physicalCoreCount) {
      self.physicalCoreCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .logicalCoreCount) {
      self.logicalCoreCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .series) {
      self.series = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineType) {
      self.machineType = value
    }
    if let value = try container.decodeIfPresent([ComputeStorageDescriptor].self, forKey: .storage)
    {
      self.storage = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.memoryMb, forKey: .memoryMb)
    try container.encode(self.physicalCoreCount, forKey: .physicalCoreCount)
    try container.encode(self.logicalCoreCount, forKey: .logicalCoreCount)
    try container.encode(self.series, forKey: .series)
    try container.encode(self.machineType, forKey: .machineType)
    try container.encode(self.storage, forKey: .storage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.ComputeEngineShapeDescriptor"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
