// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The user preferences relating to Compute Engine target platform.
public struct ComputeEnginePreferences: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Preferences concerning the machine types to consider on Compute Engine.
  public var machinePreferences: MachinePreferences? = nil

  /// License type to consider when calculating costs for virtual machine
  /// insights and recommendations. If unspecified, costs are calculated
  /// based on the default licensing plan.
  public var licenseType: LicenseType = LicenseType()

  /// Initialize a new instance of `ComputeEnginePreferences`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ComputeEnginePreferences().with { $0.machinePreferences = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.ComputeEnginePreferences"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
