// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Disk Partition details.
public struct DiskPartition: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Partition type.
  public var type: Swift.String = Swift.String()

  /// Partition file system.
  public var fileSystem: Swift.String = Swift.String()

  /// Mount pount (Linux/Windows) or drive letter (Windows).
  public var mountPoint: Swift.String = Swift.String()

  /// Partition capacity.
  public var capacityBytes: Swift.Int64 = Swift.Int64()

  /// Partition free space.
  public var freeBytes: Swift.Int64 = Swift.Int64()

  /// Partition UUID.
  public var uuid: Swift.String = Swift.String()

  /// Sub-partitions.
  public var subPartitions: GoogleCloudWKT.Recursive<DiskPartitionList>? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiskPartition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiskPartition().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let fileSystem = CodingKeys(stringValue: "fileSystem")
    static let mountPoint = CodingKeys(stringValue: "mountPoint")
    static let capacityBytes = CodingKeys(stringValue: "capacityBytes")
    static let freeBytes = CodingKeys(stringValue: "freeBytes")
    static let uuid = CodingKeys(stringValue: "uuid")
    static let subPartitions = CodingKeys(stringValue: "subPartitions")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "fileSystem",
      "mountPoint",
      "capacityBytes",
      "freeBytes",
      "uuid",
      "subPartitions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fileSystem) {
      self.fileSystem = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .mountPoint) {
      self.mountPoint = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .capacityBytes) {
      self.capacityBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .freeBytes) {
      self.freeBytes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uuid) {
      self.uuid = value
    }
    self.subPartitions = try container.decodeIfPresent(
      GoogleCloudWKT.Recursive<DiskPartitionList>.self, forKey: .subPartitions)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.fileSystem, forKey: .fileSystem)
    try container.encode(self.mountPoint, forKey: .mountPoint)
    try container.encode(self.capacityBytes, forKey: .capacityBytes)
    try container.encode(self.freeBytes, forKey: .freeBytes)
    try container.encode(self.uuid, forKey: .uuid)
    try container.encodeIfPresent(self.subPartitions, forKey: .subPartitions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.DiskPartition"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
