// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Single disk entry.
public struct DiskEntry: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Disk capacity.
  public var capacityBytes: Swift.Int64 = Swift.Int64()

  /// Disk free space.
  public var freeBytes: Swift.Int64 = Swift.Int64()

  /// Disk label.
  public var diskLabel: Swift.String = Swift.String()

  /// Disk label type (e.g. BIOS/GPT)
  public var diskLabelType: Swift.String = Swift.String()

  /// Disks interface type.
  public var interfaceType: DiskEntry.InterfaceType = DiskEntry.InterfaceType()

  /// Partition layout.
  public var partitions: DiskPartitionList? = nil

  /// Disk hardware address (e.g. 0:1 for SCSI).
  public var hwAddress: Swift.String = Swift.String()

  /// Additional details for specific platforms.
  public var platformSpecific: OneOf_PlatformSpecific? = nil

  /// Initialize a new instance of `DiskEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiskEntry().with { $0.capacityBytes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case capacityBytes = "capacityBytes"
    case freeBytes = "freeBytes"
    case diskLabel = "diskLabel"
    case diskLabelType = "diskLabelType"
    case interfaceType = "interfaceType"
    case partitions = "partitions"
    case hwAddress = "hwAddress"
    case vmware = "vmware"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.capacityBytes = try container.decode(Swift.Int64.self, forKey: .capacityBytes)
    self.freeBytes = try container.decode(Swift.Int64.self, forKey: .freeBytes)
    self.diskLabel = try container.decode(Swift.String.self, forKey: .diskLabel)
    self.diskLabelType = try container.decode(Swift.String.self, forKey: .diskLabelType)
    self.interfaceType = try container.decode(DiskEntry.InterfaceType.self, forKey: .interfaceType)
    self.partitions = try container.decodeIfPresent(DiskPartitionList.self, forKey: .partitions)
    self.hwAddress = try container.decode(Swift.String.self, forKey: .hwAddress)

    var platformSpecific: OneOf_PlatformSpecific? = nil
    let platformSpecificCheckAndSet = {
      if platformSpecific != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'platformSpecific'"))
      }
      platformSpecific = $0
    }
    if let vmware = try container.decodeIfPresent(VmwareDiskConfig?.self, forKey: .vmware) {
      try platformSpecificCheckAndSet(.vmware(vmware))
    }
    self.platformSpecific = platformSpecific
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.capacityBytes, forKey: .capacityBytes)
    try container.encode(self.freeBytes, forKey: .freeBytes)
    try container.encode(self.diskLabel, forKey: .diskLabel)
    try container.encode(self.diskLabelType, forKey: .diskLabelType)
    try container.encode(self.interfaceType, forKey: .interfaceType)
    try container.encode(self.partitions, forKey: .partitions)
    try container.encode(self.hwAddress, forKey: .hwAddress)

    if let choice = self.platformSpecific {
      switch choice {
      case .vmware(let value):
        try container.encode(value, forKey: .vmware)
      }
    }
  }

  /// Disks interface type.
  public enum InterfaceType: Codable, Equatable, Sendable {
    /// Interface type unknown or unspecified.
    case unspecified
    /// IDE interface type.
    case ide
    /// SATA interface type.
    case sata
    /// SAS interface type.
    case sas
    /// SCSI interface type.
    case scsi
    /// NVME interface type.
    case nvme
    /// FC interface type.
    case fc
    /// iSCSI interface type.
    case iscsi
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ide: return 1
      case .sata: return 2
      case .sas: return 3
      case .scsi: return 4
      case .nvme: return 5
      case .fc: return 6
      case .iscsi: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "INTERFACE_TYPE_UNSPECIFIED"
      case .ide: return "IDE"
      case .sata: return "SATA"
      case .sas: return "SAS"
      case .scsi: return "SCSI"
      case .nvme: return "NVME"
      case .fc: return "FC"
      case .iscsi: return "ISCSI"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:InterfaceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "INTERFACE_TYPE_UNSPECIFIED": self = .unspecified
      case "IDE": self = .ide
      case "SATA": self = .sata
      case "SAS": self = .sas
      case "SCSI": self = .scsi
      case "NVME": self = .nvme
      case "FC": self = .fc
      case "ISCSI": self = .iscsi
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:InterfaceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ide
      case 2: self = .sata
      case 3: self = .sas
      case 4: self = .scsi
      case 5: self = .nvme
      case 6: self = .fc
      case 7: self = .iscsi
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ide: return try container.encode(1)
      case .sata: return try container.encode(2)
      case .sas: return try container.encode(3)
      case .scsi: return try container.encode(4)
      case .nvme: return try container.encode(5)
      case .fc: return try container.encode(6)
      case .iscsi: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Additional details for specific platforms.
  public enum OneOf_PlatformSpecific: Codable, Equatable, Sendable {
    /// VMware disk details.
    indirect case vmware(VmwareDiskConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.DiskEntry"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
