// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// ErrorFrameView can be specified in ErrorFrames List and Get requests to
/// control the level of details that is returned for the original frame.
public enum ErrorFrameView: Codable, Equatable, Sendable {
  /// Value is unset. The system will fallback to the default value.
  case unspecified
  /// Include basic frame data, but not the full contents.
  case basic
  /// Include everything.
  case full
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .basic: return 1
    case .full: return 2
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "ERROR_FRAME_VIEW_UNSPECIFIED"
    case .basic: return "ERROR_FRAME_VIEW_BASIC"
    case .full: return "ERROR_FRAME_VIEW_FULL"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ErrorFrameView/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "ERROR_FRAME_VIEW_UNSPECIFIED": self = .unspecified
    case "ERROR_FRAME_VIEW_BASIC": self = .basic
    case "ERROR_FRAME_VIEW_FULL": self = .full
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ErrorFrameView/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .basic
    case 2: self = .full
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .basic: return try container.encode(1)
    case .full: return try container.encode(2)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
