// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message representing a frame which failed to be processed due to an error.
public struct ErrorFrame: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The identifier of the ErrorFrame.
  public var name: Swift.String = Swift.String()

  /// Output only. All the violations that were detected for the frame.
  public var violations: [FrameViolationEntry] = []

  /// Output only. The frame that was originally reported.
  public var originalFrame: AssetFrame? = nil

  /// Output only. Frame ingestion time.
  public var ingestionTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ErrorFrame`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ErrorFrame().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let violations = CodingKeys(stringValue: "violations")
    static let originalFrame = CodingKeys(stringValue: "originalFrame")
    static let ingestionTime = CodingKeys(stringValue: "ingestionTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "violations",
      "originalFrame",
      "ingestionTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([FrameViolationEntry].self, forKey: .violations) {
      self.violations = value
    }
    self.originalFrame = try container.decodeIfPresent(AssetFrame.self, forKey: .originalFrame)
    self.ingestionTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .ingestionTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.violations, forKey: .violations)
    try container.encodeIfPresent(self.originalFrame, forKey: .originalFrame)
    try container.encodeIfPresent(self.ingestionTime, forKey: .ingestionTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.ErrorFrame"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
