// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A resource that aggregates the validation errors found in an import job file.
public struct FileValidationReport: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the file.
  public var fileName: Swift.String = Swift.String()

  /// Partial list of rows that encountered validation error.
  public var rowErrors: [ImportRowError] = []

  /// Flag indicating that processing was aborted due to maximum number of
  /// errors.
  public var partialReport: Swift.Bool = Swift.Bool()

  /// List of file level errors.
  public var fileErrors: [ImportError] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `FileValidationReport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FileValidationReport().with { $0.fileName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let fileName = CodingKeys(stringValue: "fileName")
    static let rowErrors = CodingKeys(stringValue: "rowErrors")
    static let partialReport = CodingKeys(stringValue: "partialReport")
    static let fileErrors = CodingKeys(stringValue: "fileErrors")

    static let _knownKeys: Set<Swift.String> = [
      "fileName",
      "rowErrors",
      "partialReport",
      "fileErrors",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fileName) {
      self.fileName = value
    }
    if let value = try container.decodeIfPresent([ImportRowError].self, forKey: .rowErrors) {
      self.rowErrors = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .partialReport) {
      self.partialReport = value
    }
    if let value = try container.decodeIfPresent([ImportError].self, forKey: .fileErrors) {
      self.fileErrors = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.fileName, forKey: .fileName)
    try container.encode(self.rowErrors, forKey: .rowErrors)
    try container.encode(self.partialReport, forKey: .partialReport)
    try container.encode(self.fileErrors, forKey: .fileErrors)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.FileValidationReport"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
