// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Single fstab entry.
public struct FstabEntry: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The block special device or remote filesystem to be mounted.
  public var spec: Swift.String = Swift.String()

  /// The mount point for the filesystem.
  public var file: Swift.String = Swift.String()

  /// The type of the filesystem.
  public var vfstype: Swift.String = Swift.String()

  /// Mount options associated with the filesystem.
  public var mntops: Swift.String = Swift.String()

  /// Used by dump to determine which filesystems need to be dumped.
  public var freq: Swift.Int32 = Swift.Int32()

  /// Used by the fsck(8) program to determine the order in which filesystem
  /// checks are done at reboot time.
  public var passno: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `FstabEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FstabEntry().with { $0.spec = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.FstabEntry"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
