// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Guest OS runtime information.
public struct GuestRuntimeDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Running background services.
  public var services: RunningServiceList? = nil

  /// Running processes.
  public var processes: RunningProcessList? = nil

  /// Runtime network information (connections, ports).
  public var network: RuntimeNetworkInfo? = nil

  /// Last time the OS was booted.
  public var lastBootTime: GoogleCloudWkt.Timestamp? = nil

  /// Domain, e.g. c.stratozone-development.internal.
  public var domain: Swift.String = Swift.String()

  /// Machine name.
  public var machineName: Swift.String = Swift.String()

  /// Installed applications information.
  public var installedApps: GuestInstalledApplicationList? = nil

  /// Open files information.
  public var openFileList: OpenFileList? = nil

  /// Initialize a new instance of `GuestRuntimeDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GuestRuntimeDetails().with { $0.services = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.GuestRuntimeDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
