// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information from Guest-level collections.
public struct GuestOsDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the operating system.
  public var osName: Swift.String = Swift.String()

  /// What family the OS belong to, if known.
  public var family: OperatingSystemFamily = OperatingSystemFamily()

  /// The version of the operating system.
  public var version: Swift.String = Swift.String()

  /// OS and app configuration.
  public var config: GuestConfigDetails? = nil

  /// Runtime information.
  public var runtime: GuestRuntimeDetails? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GuestOsDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GuestOsDetails().with { $0.osName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let osName = CodingKeys(stringValue: "osName")
    static let family = CodingKeys(stringValue: "family")
    static let version = CodingKeys(stringValue: "version")
    static let config = CodingKeys(stringValue: "config")
    static let runtime = CodingKeys(stringValue: "runtime")

    static let _knownKeys: Set<Swift.String> = [
      "osName",
      "family",
      "version",
      "config",
      "runtime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .osName) {
      self.osName = value
    }
    if let value = try container.decodeIfPresent(OperatingSystemFamily.self, forKey: .family) {
      self.family = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    self.config = try container.decodeIfPresent(GuestConfigDetails.self, forKey: .config)
    self.runtime = try container.decodeIfPresent(GuestRuntimeDetails.self, forKey: .runtime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.osName, forKey: .osName)
    try container.encode(self.family, forKey: .family)
    try container.encode(self.version, forKey: .version)
    try container.encodeIfPresent(self.config, forKey: .config)
    try container.encodeIfPresent(self.runtime, forKey: .runtime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.GuestOsDetails"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
