// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Information from Guest-level collections.
public struct GuestOsDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the operating system.
  public var osName: Swift.String = Swift.String()

  /// What family the OS belong to, if known.
  public var family: OperatingSystemFamily = OperatingSystemFamily()

  /// The version of the operating system.
  public var version: Swift.String = Swift.String()

  /// OS and app configuration.
  public var config: GuestConfigDetails? = nil

  /// Runtime information.
  public var runtime: GuestRuntimeDetails? = nil

  /// Initialize a new instance of `GuestOsDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GuestOsDetails().with { $0.osName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.GuestOsDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
