// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A resource that represents the background job that imports asset frames.
public struct ImportJob: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The full name of the import job.
  public var name: Swift.String = Swift.String()

  /// User-friendly display name. Maximum length is 63 characters.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The timestamp when the import job was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The timestamp when the import job was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The timestamp when the import job was completed.
  public var completeTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The state of the import job.
  public var state: ImportJob.ImportJobState = ImportJob.ImportJobState()

  /// Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Reference to a source.
  public var assetSource: Swift.String = Swift.String()

  /// Holds the various report types of an import job.
  public var report: OneOf_Report? = nil

  /// Initialize a new instance of `ImportJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportJob().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case displayName = "displayName"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case completeTime = "completeTime"
    case state = "state"
    case labels = "labels"
    case assetSource = "assetSource"
    case validationReport = "validationReport"
    case executionReport = "executionReport"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.completeTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .completeTime)
    self.state = try container.decode(ImportJob.ImportJobState.self, forKey: .state)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.assetSource = try container.decode(Swift.String.self, forKey: .assetSource)

    var report: OneOf_Report? = nil
    let reportCheckAndSet = {
      if report != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'report'"))
      }
      report = $0
    }
    if let validationReport = try container.decodeIfPresent(
      ValidationReport?.self, forKey: .validationReport)
    {
      try reportCheckAndSet(.validationReport(validationReport))
    }
    if let executionReport = try container.decodeIfPresent(
      ExecutionReport?.self, forKey: .executionReport)
    {
      try reportCheckAndSet(.executionReport(executionReport))
    }
    self.report = report
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.completeTime, forKey: .completeTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.assetSource, forKey: .assetSource)

    if let choice = self.report {
      switch choice {
      case .validationReport(let value):
        try container.encode(value, forKey: .validationReport)
      case .executionReport(let value):
        try container.encode(value, forKey: .executionReport)
      }
    }
  }

  /// Enumerates possible states of an import job.
  public enum ImportJobState: Codable, Equatable, Sendable {
    /// Default value.
    case unspecified
    /// The import job is pending.
    case pending
    /// The processing of the import job is ongoing.
    case running
    /// The import job processing has completed.
    case completed
    /// The import job failed to be processed.
    case failed
    /// The import job is being validated.
    case validating
    /// The import job contains blocking errors.
    case failedValidation
    /// The validation of the job completed with no blocking errors.
    case ready
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .running: return 2
      case .completed: return 3
      case .failed: return 4
      case .validating: return 5
      case .failedValidation: return 6
      case .ready: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "IMPORT_JOB_STATE_UNSPECIFIED"
      case .pending: return "IMPORT_JOB_STATE_PENDING"
      case .running: return "IMPORT_JOB_STATE_RUNNING"
      case .completed: return "IMPORT_JOB_STATE_COMPLETED"
      case .failed: return "IMPORT_JOB_STATE_FAILED"
      case .validating: return "IMPORT_JOB_STATE_VALIDATING"
      case .failedValidation: return "IMPORT_JOB_STATE_FAILED_VALIDATION"
      case .ready: return "IMPORT_JOB_STATE_READY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ImportJobState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "IMPORT_JOB_STATE_UNSPECIFIED": self = .unspecified
      case "IMPORT_JOB_STATE_PENDING": self = .pending
      case "IMPORT_JOB_STATE_RUNNING": self = .running
      case "IMPORT_JOB_STATE_COMPLETED": self = .completed
      case "IMPORT_JOB_STATE_FAILED": self = .failed
      case "IMPORT_JOB_STATE_VALIDATING": self = .validating
      case "IMPORT_JOB_STATE_FAILED_VALIDATION": self = .failedValidation
      case "IMPORT_JOB_STATE_READY": self = .ready
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ImportJobState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .running
      case 3: self = .completed
      case 4: self = .failed
      case 5: self = .validating
      case 6: self = .failedValidation
      case 7: self = .ready
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .running: return try container.encode(2)
      case .completed: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .validating: return try container.encode(5)
      case .failedValidation: return try container.encode(6)
      case .ready: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Holds the various report types of an import job.
  public enum OneOf_Report: Codable, Equatable, Sendable {
    /// Output only. The report with the validation results of the import job.
    indirect case validationReport(ValidationReport?)
    /// Output only. The report with the results of running the import job.
    indirect case executionReport(ExecutionReport?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.ImportJob"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
