// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Specifies the data formats supported by Migration Center.
public enum ImportJobFormat: Codable, Equatable, Sendable {
  /// Default value.
  case unspecified
  /// RVTools format (XLSX).
  case rvtoolsXlsx
  /// RVTools format (CSV).
  case rvtoolsCsv
  /// CSV format exported from AWS using the
  /// [AWS collection
  /// script][https://github.com/GoogleCloudPlatform/aws-to-stratozone-export].
  case exportedAwsCsv
  /// CSV format exported from Azure using the
  /// [Azure collection
  /// script][https://github.com/GoogleCloudPlatform/azure-to-stratozone-export].
  case exportedAzureCsv
  /// CSV format created manually and following the StratoZone format. For more
  /// information, see [Manually create and upload data
  /// tables][https://cloud.google.com/migrate/stratozone/docs/import-data-portal].
  case stratozoneCsv
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .rvtoolsXlsx: return 1
    case .rvtoolsCsv: return 2
    case .exportedAwsCsv: return 4
    case .exportedAzureCsv: return 5
    case .stratozoneCsv: return 6
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "IMPORT_JOB_FORMAT_UNSPECIFIED"
    case .rvtoolsXlsx: return "IMPORT_JOB_FORMAT_RVTOOLS_XLSX"
    case .rvtoolsCsv: return "IMPORT_JOB_FORMAT_RVTOOLS_CSV"
    case .exportedAwsCsv: return "IMPORT_JOB_FORMAT_EXPORTED_AWS_CSV"
    case .exportedAzureCsv: return "IMPORT_JOB_FORMAT_EXPORTED_AZURE_CSV"
    case .stratozoneCsv: return "IMPORT_JOB_FORMAT_STRATOZONE_CSV"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ImportJobFormat/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "IMPORT_JOB_FORMAT_UNSPECIFIED": self = .unspecified
    case "IMPORT_JOB_FORMAT_RVTOOLS_XLSX": self = .rvtoolsXlsx
    case "IMPORT_JOB_FORMAT_RVTOOLS_CSV": self = .rvtoolsCsv
    case "IMPORT_JOB_FORMAT_EXPORTED_AWS_CSV": self = .exportedAwsCsv
    case "IMPORT_JOB_FORMAT_EXPORTED_AZURE_CSV": self = .exportedAzureCsv
    case "IMPORT_JOB_FORMAT_STRATOZONE_CSV": self = .stratozoneCsv
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ImportJobFormat/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .rvtoolsXlsx
    case 2: self = .rvtoolsCsv
    case 4: self = .exportedAwsCsv
    case 5: self = .exportedAzureCsv
    case 6: self = .stratozoneCsv
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .rvtoolsXlsx: return try container.encode(1)
    case .rvtoolsCsv: return try container.encode(2)
    case .exportedAwsCsv: return try container.encode(4)
    case .exportedAzureCsv: return try container.encode(5)
    case .stratozoneCsv: return try container.encode(6)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
