// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An insight about an asset.
public struct Insight: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var insight: OneOf_Insight? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Insight`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Insight().with { $0.migrationInsight = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let migrationInsight = CodingKeys(stringValue: "migrationInsight")
    static let genericInsight = CodingKeys(stringValue: "genericInsight")

    static let _knownKeys: Set<Swift.String> = [
      "migrationInsight",
      "genericInsight",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var insight: OneOf_Insight? = nil
    let insightCheckAndSet = {
      if insight != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'insight'"))
      }
      insight = $0
    }
    if let migrationInsight = try container.decodeIfPresent(
      MigrationInsight?.self, forKey: .migrationInsight)
    {
      try insightCheckAndSet(.migrationInsight(migrationInsight))
    }
    if let genericInsight = try container.decodeIfPresent(
      GenericInsight?.self, forKey: .genericInsight)
    {
      try insightCheckAndSet(.genericInsight(genericInsight))
    }
    self.insight = insight
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.insight {
      switch choice {
      case .migrationInsight(let value):
        try container.encode(value, forKey: .migrationInsight)
      case .genericInsight(let value):
        try container.encode(value, forKey: .genericInsight)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Insight: Codable, Equatable, Sendable {
    /// Output only. An insight about potential migrations for an asset.
    indirect case migrationInsight(MigrationInsight?)
    /// Output only. A generic insight about an asset
    indirect case genericInsight(GenericInsight?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.Insight"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
