// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of a machine.
public struct MachineDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Machine unique identifier.
  public var uuid: Swift.String = Swift.String()

  /// Machine name.
  public var machineName: Swift.String = Swift.String()

  /// Machine creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Number of CPU cores in the machine. Must be non-negative.
  public var coreCount: Swift.Int32 = Swift.Int32()

  /// The amount of memory in the machine. Must be non-negative.
  public var memoryMb: Swift.Int32 = Swift.Int32()

  /// Power state of the machine.
  public var powerState: MachineDetails.PowerState = MachineDetails.PowerState()

  /// Architecture details (vendor, CPU architecture).
  public var architecture: MachineArchitectureDetails? = nil

  /// Guest OS information.
  public var guestOs: GuestOsDetails? = nil

  /// Network details.
  public var network: MachineNetworkDetails? = nil

  /// Disk details.
  public var disks: MachineDiskDetails? = nil

  /// Platform specific information.
  public var platform: PlatformDetails? = nil

  /// Initialize a new instance of `MachineDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MachineDetails().with { $0.uuid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Machine power state.
  public enum PowerState: Codable, Equatable, Sendable {
    /// Power state is unknown.
    case unspecified
    /// The machine is preparing to enter the ACTIVE state. An instance may enter
    /// the PENDING state when it launches for the first time, or when it is
    /// started after being in the SUSPENDED state.
    case pending
    /// The machine is active.
    case active
    /// The machine is being turned off.
    case suspending
    /// The machine is off.
    case suspended
    /// The machine is being deleted from the hosting platform.
    case deleting
    /// The machine is deleted from the hosting platform.
    case deleted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .active: return 2
      case .suspending: return 3
      case .suspended: return 4
      case .deleting: return 5
      case .deleted: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "POWER_STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .active: return "ACTIVE"
      case .suspending: return "SUSPENDING"
      case .suspended: return "SUSPENDED"
      case .deleting: return "DELETING"
      case .deleted: return "DELETED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PowerState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "POWER_STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "ACTIVE": self = .active
      case "SUSPENDING": self = .suspending
      case "SUSPENDED": self = .suspended
      case "DELETING": self = .deleting
      case "DELETED": self = .deleted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PowerState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .active
      case 3: self = .suspending
      case 4: self = .suspended
      case 5: self = .deleting
      case 6: self = .deleted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .active: return try container.encode(2)
      case .suspending: return try container.encode(3)
      case .suspended: return try container.encode(4)
      case .deleting: return try container.encode(5)
      case .deleted: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.MachineDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
