// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class MigrationCenterRetry: MigrationCenterStub {
    let inner: any MigrationCenterStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any MigrationCenterStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listAssets(
      request: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListAssetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAssetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListAssetsResponse
          in
          return try await self.inner.listAssets(request: r, options: o)
        })
    }

    public func getAsset(
      request: GetAssetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.Asset {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAssetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.Asset
          in
          return try await self.inner.getAsset(request: r, options: o)
        })
    }

    public func updateAsset(
      request: UpdateAssetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.Asset {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAssetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.Asset
          in
          return try await self.inner.updateAsset(request: r, options: o)
        })
    }

    public func batchUpdateAssets(
      request: BatchUpdateAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.BatchUpdateAssetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchUpdateAssetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.BatchUpdateAssetsResponse
          in
          return try await self.inner.batchUpdateAssets(request: r, options: o)
        })
    }

    public func deleteAsset(
      request: DeleteAssetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteAssetRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAsset(request: r, options: o)
        })
    }

    public func batchDeleteAssets(
      request: BatchDeleteAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchDeleteAssetsRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.batchDeleteAssets(request: r, options: o)
        })
    }

    public func reportAssetFrames(
      request: ReportAssetFramesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ReportAssetFramesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ReportAssetFramesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ReportAssetFramesResponse
          in
          return try await self.inner.reportAssetFrames(request: r, options: o)
        })
    }

    public func aggregateAssetsValues(
      request: AggregateAssetsValuesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.AggregateAssetsValuesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AggregateAssetsValuesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.AggregateAssetsValuesResponse
          in
          return try await self.inner.aggregateAssetsValues(request: r, options: o)
        })
    }

    public func createImportJob(
      request: CreateImportJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateImportJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createImportJob(request: r, options: o)
        })
    }

    public func listImportJobs(
      request: ListImportJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListImportJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListImportJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListImportJobsResponse
          in
          return try await self.inner.listImportJobs(request: r, options: o)
        })
    }

    public func getImportJob(
      request: GetImportJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ImportJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetImportJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ImportJob
          in
          return try await self.inner.getImportJob(request: r, options: o)
        })
    }

    public func deleteImportJob(
      request: DeleteImportJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteImportJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteImportJob(request: r, options: o)
        })
    }

    public func updateImportJob(
      request: UpdateImportJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateImportJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateImportJob(request: r, options: o)
        })
    }

    public func validateImportJob(
      request: ValidateImportJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ValidateImportJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.validateImportJob(request: r, options: o)
        })
    }

    public func runImportJob(
      request: RunImportJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RunImportJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.runImportJob(request: r, options: o)
        })
    }

    public func getImportDataFile(
      request: GetImportDataFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ImportDataFile {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetImportDataFileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ImportDataFile
          in
          return try await self.inner.getImportDataFile(request: r, options: o)
        })
    }

    public func listImportDataFiles(
      request: ListImportDataFilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListImportDataFilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListImportDataFilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListImportDataFilesResponse
          in
          return try await self.inner.listImportDataFiles(request: r, options: o)
        })
    }

    public func createImportDataFile(
      request: CreateImportDataFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateImportDataFileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createImportDataFile(request: r, options: o)
        })
    }

    public func deleteImportDataFile(
      request: DeleteImportDataFileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteImportDataFileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteImportDataFile(request: r, options: o)
        })
    }

    public func listGroups(
      request: ListGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGroupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListGroupsResponse
          in
          return try await self.inner.listGroups(request: r, options: o)
        })
    }

    public func getGroup(
      request: GetGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.Group {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.Group
          in
          return try await self.inner.getGroup(request: r, options: o)
        })
    }

    public func createGroup(
      request: CreateGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGroup(request: r, options: o)
        })
    }

    public func updateGroup(
      request: UpdateGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGroup(request: r, options: o)
        })
    }

    public func deleteGroup(
      request: DeleteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGroup(request: r, options: o)
        })
    }

    public func addAssetsToGroup(
      request: AddAssetsToGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AddAssetsToGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.addAssetsToGroup(request: r, options: o)
        })
    }

    public func removeAssetsFromGroup(
      request: RemoveAssetsFromGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RemoveAssetsFromGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.removeAssetsFromGroup(request: r, options: o)
        })
    }

    public func listErrorFrames(
      request: ListErrorFramesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListErrorFramesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListErrorFramesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListErrorFramesResponse
          in
          return try await self.inner.listErrorFrames(request: r, options: o)
        })
    }

    public func getErrorFrame(
      request: GetErrorFrameRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ErrorFrame {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetErrorFrameRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ErrorFrame
          in
          return try await self.inner.getErrorFrame(request: r, options: o)
        })
    }

    public func listSources(
      request: ListSourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListSourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListSourcesResponse
          in
          return try await self.inner.listSources(request: r, options: o)
        })
    }

    public func getSource(
      request: GetSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.Source {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.Source
          in
          return try await self.inner.getSource(request: r, options: o)
        })
    }

    public func createSource(
      request: CreateSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createSource(request: r, options: o)
        })
    }

    public func updateSource(
      request: UpdateSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateSource(request: r, options: o)
        })
    }

    public func deleteSource(
      request: DeleteSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSourceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteSource(request: r, options: o)
        })
    }

    public func listPreferenceSets(
      request: ListPreferenceSetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListPreferenceSetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPreferenceSetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListPreferenceSetsResponse
          in
          return try await self.inner.listPreferenceSets(request: r, options: o)
        })
    }

    public func getPreferenceSet(
      request: GetPreferenceSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.PreferenceSet {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPreferenceSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.PreferenceSet
          in
          return try await self.inner.getPreferenceSet(request: r, options: o)
        })
    }

    public func createPreferenceSet(
      request: CreatePreferenceSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePreferenceSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPreferenceSet(request: r, options: o)
        })
    }

    public func updatePreferenceSet(
      request: UpdatePreferenceSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePreferenceSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePreferenceSet(request: r, options: o)
        })
    }

    public func deletePreferenceSet(
      request: DeletePreferenceSetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePreferenceSetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePreferenceSet(request: r, options: o)
        })
    }

    public func getSettings(
      request: GetSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.Settings {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.Settings
          in
          return try await self.inner.getSettings(request: r, options: o)
        })
    }

    public func updateSettings(
      request: UpdateSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateSettings(request: r, options: o)
        })
    }

    public func createReportConfig(
      request: CreateReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateReportConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createReportConfig(request: r, options: o)
        })
    }

    public func getReportConfig(
      request: GetReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ReportConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetReportConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ReportConfig
          in
          return try await self.inner.getReportConfig(request: r, options: o)
        })
    }

    public func listReportConfigs(
      request: ListReportConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListReportConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListReportConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListReportConfigsResponse
          in
          return try await self.inner.listReportConfigs(request: r, options: o)
        })
    }

    public func deleteReportConfig(
      request: DeleteReportConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteReportConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteReportConfig(request: r, options: o)
        })
    }

    public func createReport(
      request: CreateReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createReport(request: r, options: o)
        })
    }

    public func getReport(
      request: GetReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.Report {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.Report
          in
          return try await self.inner.getReport(request: r, options: o)
        })
    }

    public func listReports(
      request: ListReportsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudMigrationCenterV1.ListReportsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListReportsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudMigrationCenterV1.ListReportsResponse
          in
          return try await self.inner.listReports(request: r, options: o)
        })
    }

    public func deleteReport(
      request: DeleteReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteReportRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteReport(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
