// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

public struct NetworkConnection: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Connection protocol (e.g. TCP/UDP).
  public var `protocol`: Swift.String = Swift.String()

  /// Local IP address.
  public var localIpAddress: Swift.String = Swift.String()

  /// Local port.
  public var localPort: Swift.Int32 = Swift.Int32()

  /// Remote IP address.
  public var remoteIpAddress: Swift.String = Swift.String()

  /// Remote port.
  public var remotePort: Swift.Int32 = Swift.Int32()

  /// Network connection state.
  public var state: NetworkConnection.State = NetworkConnection.State()

  /// Process ID.
  public var pid: Swift.Int64 = Swift.Int64()

  /// Process or service name.
  public var processName: Swift.String = Swift.String()

  /// Initialize a new instance of `NetworkConnection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkConnection().with { $0.`protocol` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `protocol` = "protocol"
    case localIpAddress = "localIpAddress"
    case localPort = "localPort"
    case remoteIpAddress = "remoteIpAddress"
    case remotePort = "remotePort"
    case state = "state"
    case pid = "pid"
    case processName = "processName"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`protocol` = try container.decode(Swift.String.self, forKey: .`protocol`)
    self.localIpAddress = try container.decode(Swift.String.self, forKey: .localIpAddress)
    self.localPort = try container.decode(Swift.Int32.self, forKey: .localPort)
    self.remoteIpAddress = try container.decode(Swift.String.self, forKey: .remoteIpAddress)
    self.remotePort = try container.decode(Swift.Int32.self, forKey: .remotePort)
    self.state = try container.decode(NetworkConnection.State.self, forKey: .state)
    self.pid = try container.decode(Swift.Int64.self, forKey: .pid)
    self.processName = try container.decode(Swift.String.self, forKey: .processName)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.localIpAddress, forKey: .localIpAddress)
    try container.encode(self.localPort, forKey: .localPort)
    try container.encode(self.remoteIpAddress, forKey: .remoteIpAddress)
    try container.encode(self.remotePort, forKey: .remotePort)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.pid, forKey: .pid)
    try container.encode(self.processName, forKey: .processName)
  }

  /// Network connection state.
  public enum State: Codable, Equatable, Sendable {
    /// Connection state is unknown or unspecified.
    case unspecified
    /// The connection is being opened.
    case opening
    /// The connection is open.
    case `open`
    /// Listening for incoming connections.
    case listen
    /// The connection is being closed.
    case closing
    /// The connection is closed.
    case closed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .opening: return 1
      case .`open`: return 2
      case .listen: return 3
      case .closing: return 4
      case .closed: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .opening: return "OPENING"
      case .`open`: return "OPEN"
      case .listen: return "LISTEN"
      case .closing: return "CLOSING"
      case .closed: return "CLOSED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "OPENING": self = .opening
      case "OPEN": self = .`open`
      case "LISTEN": self = .listen
      case "CLOSING": self = .closing
      case "CLOSED": self = .closed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .opening
      case 2: self = .`open`
      case 3: self = .listen
      case 4: self = .closing
      case 5: self = .closed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .opening: return try container.encode(1)
      case .`open`: return try container.encode(2)
      case .listen: return try container.encode(3)
      case .closing: return try container.encode(4)
      case .closed: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.NetworkConnection"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
