// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Open file Information.
public struct OpenFileDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Opened file command.
  public var command: Swift.String = Swift.String()

  /// Opened file user.
  public var user: Swift.String = Swift.String()

  /// Opened file file type.
  public var fileType: Swift.String = Swift.String()

  /// Opened file file path.
  public var filePath: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `OpenFileDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OpenFileDetails().with { $0.command = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let command = CodingKeys(stringValue: "command")
    static let user = CodingKeys(stringValue: "user")
    static let fileType = CodingKeys(stringValue: "fileType")
    static let filePath = CodingKeys(stringValue: "filePath")

    static let _knownKeys: Set<Swift.String> = [
      "command",
      "user",
      "fileType",
      "filePath",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .command) {
      self.command = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .user) {
      self.user = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fileType) {
      self.fileType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filePath) {
      self.filePath = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.command, forKey: .command)
    try container.encode(self.user, forKey: .user)
    try container.encode(self.fileType, forKey: .fileType)
    try container.encode(self.filePath, forKey: .filePath)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.OpenFileDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
