// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Performance data sample.
public struct PerformanceSample: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Time the sample was collected.
  /// If omitted, the frame report time will be used.
  public var sampleTime: GoogleCloudWkt.Timestamp? = nil

  /// Memory usage sample.
  public var memory: MemoryUsageSample? = nil

  /// CPU usage sample.
  public var cpu: CpuUsageSample? = nil

  /// Network usage sample.
  public var network: NetworkUsageSample? = nil

  /// Disk usage sample.
  public var disk: DiskUsageSample? = nil

  /// Initialize a new instance of `PerformanceSample`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PerformanceSample().with { $0.sampleTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.PerformanceSample"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
