// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information about the platform.
public struct PlatformDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  public var vendorDetails: OneOf_VendorDetails? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PlatformDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PlatformDetails().with { $0.vmwareDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let vmwareDetails = CodingKeys(stringValue: "vmwareDetails")
    static let awsEc2Details = CodingKeys(stringValue: "awsEc2Details")
    static let azureVmDetails = CodingKeys(stringValue: "azureVmDetails")
    static let genericDetails = CodingKeys(stringValue: "genericDetails")
    static let physicalDetails = CodingKeys(stringValue: "physicalDetails")

    static let _knownKeys: Set<Swift.String> = [
      "vmwareDetails",
      "awsEc2Details",
      "azureVmDetails",
      "genericDetails",
      "physicalDetails",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var vendorDetails: OneOf_VendorDetails? = nil
    let vendorDetailsCheckAndSet = {
      if vendorDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'vendorDetails'"))
      }
      vendorDetails = $0
    }
    if let vmwareDetails = try container.decodeIfPresent(
      VmwarePlatformDetails?.self, forKey: .vmwareDetails)
    {
      try vendorDetailsCheckAndSet(.vmwareDetails(vmwareDetails))
    }
    if let awsEc2Details = try container.decodeIfPresent(
      AwsEc2PlatformDetails?.self, forKey: .awsEc2Details)
    {
      try vendorDetailsCheckAndSet(.awsEc2Details(awsEc2Details))
    }
    if let azureVmDetails = try container.decodeIfPresent(
      AzureVmPlatformDetails?.self, forKey: .azureVmDetails)
    {
      try vendorDetailsCheckAndSet(.azureVmDetails(azureVmDetails))
    }
    if let genericDetails = try container.decodeIfPresent(
      GenericPlatformDetails?.self, forKey: .genericDetails)
    {
      try vendorDetailsCheckAndSet(.genericDetails(genericDetails))
    }
    if let physicalDetails = try container.decodeIfPresent(
      PhysicalPlatformDetails?.self, forKey: .physicalDetails)
    {
      try vendorDetailsCheckAndSet(.physicalDetails(physicalDetails))
    }
    self.vendorDetails = vendorDetails
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.vendorDetails {
      switch choice {
      case .vmwareDetails(let value):
        try container.encode(value, forKey: .vmwareDetails)
      case .awsEc2Details(let value):
        try container.encode(value, forKey: .awsEc2Details)
      case .azureVmDetails(let value):
        try container.encode(value, forKey: .azureVmDetails)
      case .genericDetails(let value):
        try container.encode(value, forKey: .genericDetails)
      case .physicalDetails(let value):
        try container.encode(value, forKey: .physicalDetails)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_VendorDetails: Codable, Equatable, Sendable {
    /// VMware specific details.
    indirect case vmwareDetails(VmwarePlatformDetails?)
    /// AWS EC2 specific details.
    indirect case awsEc2Details(AwsEc2PlatformDetails?)
    /// Azure VM specific details.
    indirect case azureVmDetails(AzureVmPlatformDetails?)
    /// Generic platform details.
    indirect case genericDetails(GenericPlatformDetails?)
    /// Physical machines platform details.
    indirect case physicalDetails(PhysicalPlatformDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.PlatformDetails"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
