// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Preferences concerning Sole Tenancy nodes and VMs.
public struct SoleTenancyPreferences: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// CPU overcommit ratio.
  /// Acceptable values are between 1.0 and 2.0 inclusive.
  public var cpuOvercommitRatio: Swift.Double = Swift.Double()

  /// Sole Tenancy nodes maintenance policy.
  public var hostMaintenancePolicy: SoleTenancyPreferences.HostMaintenancePolicy =
    SoleTenancyPreferences.HostMaintenancePolicy()

  /// Commitment plan to consider when calculating costs for virtual machine
  /// insights and recommendations.
  /// If you are unsure which value to set, a 3 year commitment plan is often a
  /// good value to start with.
  public var commitmentPlan: SoleTenancyPreferences.CommitmentPlan =
    SoleTenancyPreferences.CommitmentPlan()

  /// A list of sole tenant node types.
  /// An empty list means that all possible node types will be considered.
  public var nodeTypes: [SoleTenantNodeType] = []

  /// Initialize a new instance of `SoleTenancyPreferences`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SoleTenancyPreferences().with { $0.cpuOvercommitRatio = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Sole Tenancy nodes maintenance policy.
  public enum HostMaintenancePolicy: Codable, Equatable, Sendable {
    /// Unspecified host maintenance policy.
    case unspecified
    /// Default host maintenance policy.
    case `default`
    /// Restart in place host maintenance policy.
    case restartInPlace
    /// Migrate within node group host maintenance policy.
    case migrateWithinNodeGroup
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`default`: return 1
      case .restartInPlace: return 2
      case .migrateWithinNodeGroup: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HOST_MAINTENANCE_POLICY_UNSPECIFIED"
      case .`default`: return "HOST_MAINTENANCE_POLICY_DEFAULT"
      case .restartInPlace: return "HOST_MAINTENANCE_POLICY_RESTART_IN_PLACE"
      case .migrateWithinNodeGroup: return "HOST_MAINTENANCE_POLICY_MIGRATE_WITHIN_NODE_GROUP"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HostMaintenancePolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HOST_MAINTENANCE_POLICY_UNSPECIFIED": self = .unspecified
      case "HOST_MAINTENANCE_POLICY_DEFAULT": self = .`default`
      case "HOST_MAINTENANCE_POLICY_RESTART_IN_PLACE": self = .restartInPlace
      case "HOST_MAINTENANCE_POLICY_MIGRATE_WITHIN_NODE_GROUP": self = .migrateWithinNodeGroup
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HostMaintenancePolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`default`
      case 2: self = .restartInPlace
      case 3: self = .migrateWithinNodeGroup
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`default`: return try container.encode(1)
      case .restartInPlace: return try container.encode(2)
      case .migrateWithinNodeGroup: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of committed use discount.
  public enum CommitmentPlan: Codable, Equatable, Sendable {
    /// Unspecified commitment plan.
    case unspecified
    /// No commitment plan (on-demand usage).
    case onDemand
    /// 1 year commitment.
    case commitment1Year
    /// 3 years commitment.
    case commitment3Year
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .onDemand: return 1
      case .commitment1Year: return 2
      case .commitment3Year: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMMITMENT_PLAN_UNSPECIFIED"
      case .onDemand: return "ON_DEMAND"
      case .commitment1Year: return "COMMITMENT_1_YEAR"
      case .commitment3Year: return "COMMITMENT_3_YEAR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CommitmentPlan/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMMITMENT_PLAN_UNSPECIFIED": self = .unspecified
      case "ON_DEMAND": self = .onDemand
      case "COMMITMENT_1_YEAR": self = .commitment1Year
      case "COMMITMENT_3_YEAR": self = .commitment3Year
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CommitmentPlan/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .onDemand
      case 2: self = .commitment1Year
      case 3: self = .commitment3Year
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .onDemand: return try container.encode(1)
      case .commitment1Year: return try container.encode(2)
      case .commitment3Year: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.SoleTenancyPreferences"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
