// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Source represents an object from which asset information is
/// streamed to Migration Center.
public struct Source: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The full name of the source.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp when the source was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The timestamp when the source was last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// User-friendly display name.
  public var displayName: Swift.String = Swift.String()

  /// Free-text description.
  public var description: Swift.String = Swift.String()

  /// Data source type.
  public var type: Source.SourceType = Source.SourceType()

  /// The information confidence of the source.
  /// The higher the value, the higher the confidence.
  public var priority: Swift.Int32 = Swift.Int32()

  /// If `true`, the source is managed by other service(s).
  public var managed: Swift.Bool = Swift.Bool()

  /// Output only. Number of frames that are still being processed.
  public var pendingFrameCount: Swift.Int32 = Swift.Int32()

  /// Output only. The number of frames that were reported by the source and
  /// contained errors.
  public var errorFrameCount: Swift.Int32 = Swift.Int32()

  /// Output only. The state of the source.
  public var state: Source.State = Source.State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Source`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Source().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let type = CodingKeys(stringValue: "type")
    static let priority = CodingKeys(stringValue: "priority")
    static let managed = CodingKeys(stringValue: "managed")
    static let pendingFrameCount = CodingKeys(stringValue: "pendingFrameCount")
    static let errorFrameCount = CodingKeys(stringValue: "errorFrameCount")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "displayName",
      "description",
      "type",
      "priority",
      "managed",
      "pendingFrameCount",
      "errorFrameCount",
      "state",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Source.SourceType.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .priority) {
      self.priority = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .managed) {
      self.managed = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pendingFrameCount) {
      self.pendingFrameCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .errorFrameCount) {
      self.errorFrameCount = value
    }
    if let value = try container.decodeIfPresent(Source.State.self, forKey: .state) {
      self.state = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.priority, forKey: .priority)
    try container.encode(self.managed, forKey: .managed)
    try container.encode(self.pendingFrameCount, forKey: .pendingFrameCount)
    try container.encode(self.errorFrameCount, forKey: .errorFrameCount)
    try container.encode(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum SourceType: Codable, Equatable, Sendable {
    /// Unspecified
    case unknown
    /// Manually uploaded file (e.g. CSV)
    case upload
    /// Guest-level info
    case guestOsScan
    /// Inventory-level scan
    case inventoryScan
    /// Third-party owned sources.
    case custom
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .upload: return 1
      case .guestOsScan: return 2
      case .inventoryScan: return 3
      case .custom: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "SOURCE_TYPE_UNKNOWN"
      case .upload: return "SOURCE_TYPE_UPLOAD"
      case .guestOsScan: return "SOURCE_TYPE_GUEST_OS_SCAN"
      case .inventoryScan: return "SOURCE_TYPE_INVENTORY_SCAN"
      case .custom: return "SOURCE_TYPE_CUSTOM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SourceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SOURCE_TYPE_UNKNOWN": self = .unknown
      case "SOURCE_TYPE_UPLOAD": self = .upload
      case "SOURCE_TYPE_GUEST_OS_SCAN": self = .guestOsScan
      case "SOURCE_TYPE_INVENTORY_SCAN": self = .inventoryScan
      case "SOURCE_TYPE_CUSTOM": self = .custom
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SourceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .upload
      case 2: self = .guestOsScan
      case 3: self = .inventoryScan
      case 4: self = .custom
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode("SOURCE_TYPE_UNKNOWN")
      case .upload: return try container.encode("SOURCE_TYPE_UPLOAD")
      case .guestOsScan: return try container.encode("SOURCE_TYPE_GUEST_OS_SCAN")
      case .inventoryScan: return try container.encode("SOURCE_TYPE_INVENTORY_SCAN")
      case .custom: return try container.encode("SOURCE_TYPE_CUSTOM")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Enumerates possible states of a source.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// The source is active and ready to be used.
    case active
    /// In the process of being deleted.
    case deleting
    /// Source is in an invalid state. Asset frames reported to it will be
    /// ignored.
    case invalid
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .deleting: return 2
      case .invalid: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .invalid: return "INVALID"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "INVALID": self = .invalid
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .deleting
      case 3: self = .invalid
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .deleting: return try container.encode("DELETING")
      case .invalid: return try container.encode("INVALID")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.Source"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
