// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// VMware disk config details.
public struct VmwareDiskConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// VMDK backing type.
  public var backingType: VmwareDiskConfig.BackingType = VmwareDiskConfig.BackingType()

  /// Is VMDK shared with other VMs.
  public var shared: Swift.Bool = Swift.Bool()

  /// VMDK disk mode.
  public var vmdkMode: VmwareDiskConfig.VmdkMode = VmwareDiskConfig.VmdkMode()

  /// RDM compatibility mode.
  public var rdmCompatibility: VmwareDiskConfig.RdmCompatibility =
    VmwareDiskConfig.RdmCompatibility()

  /// Initialize a new instance of `VmwareDiskConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VmwareDiskConfig().with { $0.backingType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// VMDK backing type possible values.
  public enum BackingType: Codable, Equatable, Sendable {
    /// Default value.
    case unspecified
    /// Flat v1.
    case flatV1
    /// Flat v2.
    case flatV2
    /// Persistent memory, also known as Non-Volatile Memory (NVM).
    case pmem
    /// Raw Disk Memory v1.
    case rdmV1
    /// Raw Disk Memory v2.
    case rdmV2
    /// SEsparse is a snapshot format introduced in vSphere 5.5 for large disks.
    case sesparse
    /// SEsparse v1.
    case sesparseV1
    /// SEsparse v1.
    case sesparseV2
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .flatV1: return 1
      case .flatV2: return 2
      case .pmem: return 3
      case .rdmV1: return 4
      case .rdmV2: return 5
      case .sesparse: return 6
      case .sesparseV1: return 7
      case .sesparseV2: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BACKING_TYPE_UNSPECIFIED"
      case .flatV1: return "BACKING_TYPE_FLAT_V1"
      case .flatV2: return "BACKING_TYPE_FLAT_V2"
      case .pmem: return "BACKING_TYPE_PMEM"
      case .rdmV1: return "BACKING_TYPE_RDM_V1"
      case .rdmV2: return "BACKING_TYPE_RDM_V2"
      case .sesparse: return "BACKING_TYPE_SESPARSE"
      case .sesparseV1: return "BACKING_TYPE_SESPARSE_V1"
      case .sesparseV2: return "BACKING_TYPE_SESPARSE_V2"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BackingType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BACKING_TYPE_UNSPECIFIED": self = .unspecified
      case "BACKING_TYPE_FLAT_V1": self = .flatV1
      case "BACKING_TYPE_FLAT_V2": self = .flatV2
      case "BACKING_TYPE_PMEM": self = .pmem
      case "BACKING_TYPE_RDM_V1": self = .rdmV1
      case "BACKING_TYPE_RDM_V2": self = .rdmV2
      case "BACKING_TYPE_SESPARSE": self = .sesparse
      case "BACKING_TYPE_SESPARSE_V1": self = .sesparseV1
      case "BACKING_TYPE_SESPARSE_V2": self = .sesparseV2
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BackingType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .flatV1
      case 2: self = .flatV2
      case 3: self = .pmem
      case 4: self = .rdmV1
      case 5: self = .rdmV2
      case 6: self = .sesparse
      case 7: self = .sesparseV1
      case 8: self = .sesparseV2
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .flatV1: return try container.encode(1)
      case .flatV2: return try container.encode(2)
      case .pmem: return try container.encode(3)
      case .rdmV1: return try container.encode(4)
      case .rdmV2: return try container.encode(5)
      case .sesparse: return try container.encode(6)
      case .sesparseV1: return try container.encode(7)
      case .sesparseV2: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// VMDK disk mode.
  public enum VmdkMode: Codable, Equatable, Sendable {
    /// VMDK disk mode unspecified or unknown.
    case unspecified
    /// Dependent disk mode.
    case dependent
    /// Independent - Persistent disk mode.
    case independentPersistent
    /// Independent - Nonpersistent disk mode.
    case independentNonpersistent
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dependent: return 1
      case .independentPersistent: return 2
      case .independentNonpersistent: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VMDK_MODE_UNSPECIFIED"
      case .dependent: return "DEPENDENT"
      case .independentPersistent: return "INDEPENDENT_PERSISTENT"
      case .independentNonpersistent: return "INDEPENDENT_NONPERSISTENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VmdkMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VMDK_MODE_UNSPECIFIED": self = .unspecified
      case "DEPENDENT": self = .dependent
      case "INDEPENDENT_PERSISTENT": self = .independentPersistent
      case "INDEPENDENT_NONPERSISTENT": self = .independentNonpersistent
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VmdkMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dependent
      case 2: self = .independentPersistent
      case 3: self = .independentNonpersistent
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .dependent: return try container.encode(1)
      case .independentPersistent: return try container.encode(2)
      case .independentNonpersistent: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// RDM compatibility mode.
  public enum RdmCompatibility: Codable, Equatable, Sendable {
    /// Compatibility mode unspecified or unknown.
    case unspecified
    /// Physical compatibility mode.
    case physicalCompatibility
    /// Virtual compatibility mode.
    case virtualCompatibility
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .physicalCompatibility: return 1
      case .virtualCompatibility: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RDM_COMPATIBILITY_UNSPECIFIED"
      case .physicalCompatibility: return "PHYSICAL_COMPATIBILITY"
      case .virtualCompatibility: return "VIRTUAL_COMPATIBILITY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RdmCompatibility/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RDM_COMPATIBILITY_UNSPECIFIED": self = .unspecified
      case "PHYSICAL_COMPATIBILITY": self = .physicalCompatibility
      case "VIRTUAL_COMPATIBILITY": self = .virtualCompatibility
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RdmCompatibility/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .physicalCompatibility
      case 2: self = .virtualCompatibility
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .physicalCompatibility: return try container.encode(1)
      case .virtualCompatibility: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.VmwareDiskConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
