// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The user preferences relating to Google Cloud VMware Engine target platform.
public struct VmwareEnginePreferences: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// CPU overcommit ratio.
  /// Acceptable values are between 1.0 and 8.0, with 0.1 increment.
  public var cpuOvercommitRatio: Swift.Double = Swift.Double()

  /// Memory overcommit ratio.
  /// Acceptable values are 1.0, 1.25, 1.5, 1.75 and 2.0.
  public var memoryOvercommitRatio: Swift.Double = Swift.Double()

  /// The Deduplication and Compression ratio is based on the logical (Used
  /// Before) space required to store data before applying deduplication and
  /// compression, in relation to the physical (Used After) space required after
  /// applying deduplication and compression. Specifically, the ratio is the Used
  /// Before space divided by the Used After space. For example, if the Used
  /// Before space is 3 GB, but the physical Used After space is 1 GB, the
  /// deduplication and compression ratio is 3x. Acceptable values are
  /// between 1.0 and 4.0.
  public var storageDeduplicationCompressionRatio: Swift.Double = Swift.Double()

  /// Commitment plan to consider when calculating costs for virtual machine
  /// insights and recommendations.
  /// If you are unsure which value to set, a 3 year commitment plan is often a
  /// good value to start with.
  public var commitmentPlan: VmwareEnginePreferences.CommitmentPlan =
    VmwareEnginePreferences.CommitmentPlan()

  /// Initialize a new instance of `VmwareEnginePreferences`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VmwareEnginePreferences().with { $0.cpuOvercommitRatio = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Type of committed use discount.
  public enum CommitmentPlan: Codable, Equatable, Sendable {
    /// Unspecified commitment plan.
    case unspecified
    /// No commitment plan (on-demand usage).
    case onDemand
    /// 1 year commitment (monthly payments).
    case commitment1YearMonthlyPayments
    /// 3 year commitment (monthly payments).
    case commitment3YearMonthlyPayments
    /// 1 year commitment (upfront payment).
    case commitment1YearUpfrontPayment
    /// 3 years commitment (upfront payment).
    case commitment3YearUpfrontPayment
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .onDemand: return 1
      case .commitment1YearMonthlyPayments: return 2
      case .commitment3YearMonthlyPayments: return 3
      case .commitment1YearUpfrontPayment: return 4
      case .commitment3YearUpfrontPayment: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMMITMENT_PLAN_UNSPECIFIED"
      case .onDemand: return "ON_DEMAND"
      case .commitment1YearMonthlyPayments: return "COMMITMENT_1_YEAR_MONTHLY_PAYMENTS"
      case .commitment3YearMonthlyPayments: return "COMMITMENT_3_YEAR_MONTHLY_PAYMENTS"
      case .commitment1YearUpfrontPayment: return "COMMITMENT_1_YEAR_UPFRONT_PAYMENT"
      case .commitment3YearUpfrontPayment: return "COMMITMENT_3_YEAR_UPFRONT_PAYMENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CommitmentPlan/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMMITMENT_PLAN_UNSPECIFIED": self = .unspecified
      case "ON_DEMAND": self = .onDemand
      case "COMMITMENT_1_YEAR_MONTHLY_PAYMENTS": self = .commitment1YearMonthlyPayments
      case "COMMITMENT_3_YEAR_MONTHLY_PAYMENTS": self = .commitment3YearMonthlyPayments
      case "COMMITMENT_1_YEAR_UPFRONT_PAYMENT": self = .commitment1YearUpfrontPayment
      case "COMMITMENT_3_YEAR_UPFRONT_PAYMENT": self = .commitment3YearUpfrontPayment
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CommitmentPlan/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .onDemand
      case 2: self = .commitment1YearMonthlyPayments
      case 3: self = .commitment3YearMonthlyPayments
      case 4: self = .commitment1YearUpfrontPayment
      case 5: self = .commitment3YearUpfrontPayment
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .onDemand: return try container.encode(1)
      case .commitment1YearMonthlyPayments: return try container.encode(2)
      case .commitment3YearMonthlyPayments: return try container.encode(3)
      case .commitment1YearUpfrontPayment: return try container.encode(4)
      case .commitment3YearUpfrontPayment: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.migrationcenter.v1.VmwareEnginePreferences"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
